/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package bootcamp.chapter3

class App {
    val greeting: String
        get() {
            return "Hello "
        }
}

fun main(args: Array<String>) {

    println("${App().greeting} ${args[0]}" )
    val isUnit = println("Yes, I am an Unit")
    println(isUnit)
    val temperature = 51
    val isHot = temperature > 50
    val message = "The temperature is ${ if (isHot) " too warm " else  "Ok" }  "
    println(message)
    val feeding = FeedFish()
    feeding.feedTheFish()
}
